	.file	"for-loop.cpp"
	.text
	.globl	main
	.type	main, @function
main:
.LFB0:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset 6, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register 6
	movl	$10, -8(%rbp)
	movl	$0, -4(%rbp)
.L3:
	cmpl	$15, -4(%rbp)
	jg	.L2
	addl	$1, -8(%rbp)
	addl	$1, -4(%rbp)
	jmp	.L3
.L2:
	movl	$0, %eax
	popq	%rbp
	.cfi_def_cfa 7, 8
	ret
	.cfi_endproc
.LFE0:
	.size	main, .-main
	.ident	"GCC: (GNU) 10.2.0"
	.section	.note.GNU-stack,"",@progbits
